#updateserver.yml
server:
  service:
    type: LoadBalancer

repoServer:




  podLabels:
    azure.workload.identity/use: "true"

    

configs:
  repositories:
    secretchildapphelm:
      type: helm
      name: helm-nginx
      url: acrwinter.azurecr.io/helm
      enableOCI: "true"
      useAzureWorkloadIdentity: "true"

    secretchildapphelm2:
      type: helm
      name: not-working
      url: palam2.azurecr.io/helm
      enableOCI: "true"
      useAzureWorkloadIdentity: "true"