name: Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

# env:
  
#   ARM_CLIENT_ID: 
#   ARM_TENANT_ID: 
#   ARM_SUBSCRIPTION_ID: 

jobs:

  workflow-terraform-plan-apply:
    name: Workflow-Terraform-plan-apply
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug files
        run: |
          echo "Current directory:"
          pwd

          echo ""
          echo "Repository files:"
          find . -type f | sort

          echo ""
          echo "Values directory:"
          ls -la values

          echo ""
          echo "values.yml content:"
          cat values/values.yml

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: f514a3f7-9ee6-462a-be71-6970edf8a03a
          tenant-id: 5f8d3f88-8e5b-4e25-9d00-e62229c9cc71
          subscription-id: 228a46db-66c5-4a23-9ed7-677a552990bc
# 
      - name: azure/use-kubelogin@v1
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.24'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve tfplan